# Generated by Django 4.2.7 on 2025-07-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('employe', 'Employé')], default='employe', max_length=10),
        ),
    ]
