# Generated by Django 4.2.7 on 2025-07-17 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='statut',
            field=models.CharField(choices=[('valide', 'Validé automatiquement'), ('attente', 'En attente de validation'), ('rejete', 'Rejeté'), ('accepte', 'Validé par manager')], default='attente', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mouvement_attente', 'Mouvement en attente de validation'), ('mouvement_valide', 'Mouvement validé'), ('mouvement_rejete', 'Mouvement rejeté')], max_length=30)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL)),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stock.mouvement')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date'],
            },
        ),
    ]
