# Generated by Django 4.2.7 on 2025-07-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_produit_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='seuil_mouvement',
            field=models.IntegerField(default=0),
        ),
    ]
