# Generated by Django 4.2.7 on 2025-07-15 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('tache', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plannings', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.magasin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Plannings',
                'ordering': ['-date', 'heure_debut'],
                'unique_together': {('user', 'date', 'heure_debut')},
            },
        ),
    ]
