# Generated by Django 4.2.7 on 2025-07-06 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magasin_nom', models.CharField(max_length=200)),
                ('date_pointage', models.DateTimeField()),
                ('heure_entree', models.DateTimeField(blank=True, null=True)),
                ('heure_sortie', models.DateTimeField(blank=True, null=True)),
                ('pause_entree', models.DateTimeField(blank=True, null=True)),
                ('pause_sortie', models.DateTimeField(blank=True, null=True)),
                ('duree_pause', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.CharField(choices=[('arrivee', 'Arrivée'), ('depart', 'Départ'), ('pause_entree', 'Début pause'), ('pause_sortie', 'Fin pause')], max_length=20)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.magasin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date_pointage'],
            },
        ),
    ]
