# Generated by Django 4.2.7 on 2025-07-09 09:17

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-date_pointage', '-created_at'], 'verbose_name': 'Présence', 'verbose_name_plural': 'Présences'},
        ),
        migrations.AddField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='date_pointage',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='presence',
            name='type',
            field=models.CharField(choices=[('arrivee', 'Arrivée'), ('depart', 'Départ'), ('pause_entree', 'Début pause'), ('pause_sortie', 'Fin pause')], default='arrivee', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('user', 'date_pointage')},
        ),
    ]
