# Generated by Django 4.2.7 on 2025-07-14 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
        ('attendance', '0002_alter_presence_options_presence_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('tache', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('magasin_nom', models.CharField(max_length=200)),
                ('date_pointage', models.DateField()),
                ('heure_entree', models.DateTimeField(blank=True, null=True)),
                ('heure_sortie', models.DateTimeField(blank=True, null=True)),
                ('pause_entree', models.DateTimeField(blank=True, null=True)),
                ('pause_sortie', models.DateTimeField(blank=True, null=True)),
                ('duree_pause', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.CharField(choices=[('arrivee', 'Arrivée'), ('depart', 'Départ'), ('pause_entree', 'Début pause'), ('pause_sortie', 'Fin pause')], default='arrivee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plannings', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.magasin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date_pointage', '-created_at'],
                'unique_together': {('user', 'date_pointage')},
            },
        ),
    ]
