# Generated by Django 4.2.7 on 2025-07-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_planning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planning',
        ),
    ]
